### PR TITLE
Features and bug fixes

### PR DESCRIPTION
**Pull request by danilojr-delacruz**
Changes:

- Fixed bug with Vanilla Signature Features
- Add normalization_method parameter to choose between level and sum normalisation for truncated signatures. (For comparability with PDE kernel). Defaults preserved
- Implement 1D Version of cos(XW+b) in static/features.py
- Generalise DP to have internal_size so can do RFSF-DP with 1D version

- **Typos / missed refactor (undefined variables)**:
  - GaussianRandomProjection Outer Product Z -> X
  - subsample_outer_prod_comps -> subsampled_outer_prod
  - X_proj = X in VerySparseRandomProjection

### CODE REVIEW

**Comment by tgcsaba** [comment]
Thanks, but for now please remove normalization type changes, as it does not make a difference, in fact level-wise normalization is desired so that all levels are bounded within the unit ball as required for robustness, see [here](https://arxiv.org/pdf/1810.10971) for details

**Comment by tgcsaba** [comment]
Actually can you put the 1D RFF, DP internal size and the projection is None fix into a separate request?

Thanks!

**Comment by danilojr-delacruz** [comment]
Hi Csaba, I have removed "Typos / missed refactor (undefined variables)" as it seems you have already updated this in main.

I have also removed normalisation in this pull request.

**Comment by tgcsaba** [comment]
Thanks, merged!

**Pull request merged**
